# -*- coding: utf-8 -*-
"""
run_demo.py
============
Runs the real engine (not mocked output) for three farmer priority profiles
and writes:
  data/snapshots/scorecard_<profile>.json   -- full ScoreCard, machine-readable
  docs/demo_report.md                        -- human-readable version, for
                                                the ZRF "in-person model" and
                                                the NASA pitch alike

Usage:  PYTHONPATH=src python3 run_demo.py
"""
from __future__ import annotations

import json
import sys
from dataclasses import asdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

from fieldshift.engine.pipeline import run

ROOT = Path(__file__).resolve().parent

PROFILES = {
    "soil_first": {"soil_health": 0.40, "water_saving": 0.25, "income": 0.15,
                  "risk": 0.10, "labour": 0.10},
    "water_first": {"soil_health": 0.20, "water_saving": 0.45, "income": 0.15,
                   "risk": 0.15, "labour": 0.05},
    "income_first": {"soil_health": 0.15, "water_saving": 0.15, "income": 0.45,
                    "risk": 0.15, "labour": 0.10},
}


def scorecard_to_dict(sc) -> dict:
    d = asdict(sc)
    return d


def main():
    (ROOT / "data" / "snapshots").mkdir(parents=True, exist_ok=True)
    report_lines = [
        "# Field Shift -- demo run (real engine output, synthetic weather)",
        "",
        "Generated by `run_demo.py` against the actual scoring engine in",
        "`src/fieldshift/engine/` -- these are not mocked numbers. Weather is",
        "synthetic (see `engine/weather.py`); swap in a live NASA POWER/IMERG/",
        "SMAP pull per blueprint Section 5.3 before treating results as real",
        "field guidance. Crop-library caveats are in `config/crops.yaml`.",
        "",
    ]

    for profile_name, weights in PROFILES.items():
        sc = run(weights)
        out_path = ROOT / "data" / "snapshots" / f"scorecard_{profile_name}.json"
        out_path.write_text(json.dumps(scorecard_to_dict(sc), indent=2, default=str), encoding="utf-8")

        report_lines.append(f"## Priority profile: `{profile_name}`")
        report_lines.append("")
        report_lines.append("Weights: " + ", ".join(f"{k}={v:.2f}" for k, v in weights.items()))
        report_lines.append("")
        report_lines.append("| Rank | Rotation | Score | Max regret | Pareto | Top-1 prob | Irrigation (mm) | Soil health | Income (BDT/ha) |")
        report_lines.append("|---|---|---|---|---|---|---|---|---|")
        for i, opt in enumerate(sc.options, start=1):
            base = opt.indicators_by_scenario["baseline"]
            report_lines.append(
                f"| {i} | {opt.rotation.label} | {opt.mean_score:.3f} | {opt.max_regret:.3f} | "
                f"{'yes' if opt.pareto_optimal else 'no'} | {opt.rank_probability_top1:.2f} | "
                f"{base.irrigation_requirement_mm:.0f} | {base.soil_health_index:.0f} | "
                f"{base.income_proxy_bdt_per_ha:.0f} |"
            )
        report_lines.append("")
        if sc.rejected:
            report_lines.append("Rejected candidates:")
            for rid, reason in sc.rejected:
                report_lines.append(f"- **{rid}**: {reason}")
            report_lines.append("")

    report_lines.append("## Caveats (same every run -- see ScoreCard.caveats)")
    for c in sc.caveats:
        report_lines.append(f"- {c}")

    (ROOT / "docs" / "demo_report.md").write_text("\n".join(report_lines), encoding="utf-8")
    print(f"Wrote {len(PROFILES)} scorecards to data/snapshots/ and docs/demo_report.md")


if __name__ == "__main__":
    main()
